##
## EPITECH PROJECT, 2021
## B-SEC-500-MPL-5-1-caesar-tom.treboulou
## File description:
## Makefile
##

all: 	
		cp src/challenge01.py challenge01
		cp src/challenge02.py challenge02
		cp src/challenge03.py challenge03
		cp src/challenge04.py challenge04
		cp src/challenge05.py challenge05
		cp src/challenge06.py challenge06
		cp src/challenge07.py challenge07
		cp src/challenge08.py challenge08
		cp src/challenge09.py challenge09
		cp src/challenge10.py challenge10
		cp src/challenge11.py challenge11
		cp src/challenge12.py challenge12
		cp src/challenge13.py challenge13
		cp src/challenge14.py challenge14

clean:	
		rm -f challenge01
		rm -f challenge02
		rm -f challenge03
		rm -f challenge04
		rm -f challenge05
		rm -f challenge06
		rm -f challenge07
		rm -f challenge08
		rm -f challenge09
		rm -f challenge10
		rm -f challenge11
		rm -f challenge12
		rm -f challenge13
		rm -f challenge14

fclean: clean

re: fclean all

.PHONY: clean fclean all re